import { fileURLToPath } from 'url';
// Adds/updates the procedural props in public/assets/manifest.json (same schema as the other model entries)
// and the one-line procedural-props credit in public/assets/CREDITS.md.  usage: node pipeline/props/manifest_add.mjs
import fs from 'fs';
const R = fileURLToPath(new URL('../..', import.meta.url)).replace(/\\/g, '/').replace(/\/$/, '');
const B = R + '/pipeline/props/_build';
const SOURCE = 'procedural (HouseListing pipeline/props)';
const FR = 'FLOOR-REFERENCED: y=0 is the finished floor (geometry floats), back (-Z) face goes flush to the wall. ';
const PROPS = {
  fridge_modern: ['kitchen', 'tall stainless fridge-freezer, bar handles, door display; front +Z, back against wall'],
  kitchen_sink: ['kitchen', 'undermount steel sink + black gooseneck mixer. variants: sink_worktop (1.2x0.62 m quartz worktop module, top at y=0.23), sink_bowl (bowl only, flange top = max Y, needs a 0.54x0.40 cut-out), mixer_tap'],
  toaster: ['kitchen', 'brushed-steel 2-slice toaster (worktop prop)'],
  toilet_wall_hung: ['bath', FR + 'wall-hung WC (lid closed) + black dual flush plate at 1.0 m'],
  bathtub_freestanding: ['bath', 'freestanding oval white bathtub, 1.70 m (length along X)'],
  bathroom_vanity: ['bath', FR + 'wall-hung oak vanity (top at 0.85 m), vessel basin, black mixer, round black mirror (centre 1.48 m)'],
  towel_folded: ['bath', 'single folded white bath towel (shelf/vanity/bed prop)'],
  towel_stack: ['bath', 'stack of 4 folded towels (2 white, 2 anthracite)'],
  washing_machine: ['laundry', 'front-loading washing machine, glass porthole door; front +Z'],
  sun_lounger: ['outdoor', 'teak sun lounger with white cushions, backrest up; foot end +Z'],
  parasol_cantilever: ['outdoor', 'cantilever parasol, 3x3 m off-white canopy, anthracite mast on slab base (mast at -X)'],
  bicycle: ['garage', 'city bike 700c, sage frame, gumwall tyres, on kickstand (length along X)'],
  office_chair: ['office', 'mesh-back office chair, 5-star aluminium base; front +Z'],
  floor_lamp_arc: ['lighting', 'arc floor lamp, marble base at -X, shade reaches +X (emissive LED disc)'],
  hanging_egg_chair: ['outdoor', 'rattan hanging egg chair on black C-stand (alpha-masked weave); opening faces +Z'],
  bed_double_modern: ['bedroom', 'modern upholstered double bed 160x200, duvet, pillows, throw; headboard at -Z (wall)'],
  rug_rect_200x300: ['decor', 'low-pile wool rug 2x3 m, ivory with charcoal lattice, fringed short ends'],
  rug_round_160: ['decor', 'round low-pile rug 1.6 m, warm grey tone-on-tone, charcoal bound edge'],
  car_suv: ['garage', 'graphite metallic SUV (XC90-like massing), stylised-realistic; nose +Z'],
  // ---- P07 indoor props (round 2: stand-ins for the Poly Haven set, same names as scripts/assets/models.json)
  armchair_modern: ['living', 'oat boucle lounge armchair, piped loose cushions, rust pillow, splayed oak legs; front +Z'],
  lounge_chair_midcentury: ['living', 'mid-century lounge chair, walnut ply shells, black leather cushions, swivel base; front +Z'],
  coffee_table_round_marble: ['living', 'round 0.9 m marble-top coffee table on fluted smoked-oak drum, books + brass dish'],
  side_table_oak: ['living', 'oak side table / nightstand with drawer (brass knob) and lower shelf with paperbacks; drawer +Z'],
  side_table_tall: ['living', 'tall round walnut side table on black tripod, magazines on lower ring'],
  gaming_console: ['living', 'white game console with LED strip + controller'],
  pendant_lamp_modern: ['lighting', 'smoked-brass dome pendant, emissive opal diffuser; shade bottom y=0, canopy at y=0.97'],
  desk_lamp: ['lighting', 'black architect desk lamp with springs + warm LED (built 0.53 m tall, use scale ~0.7)'],
  vase_ceramic_tall: ['decor', 'tall sand-glaze stoneware vase with dried pampas'],
  vase_ceramic_02: ['decor', 'squat celadon bud vase'],
  vase_ceramic_03: ['decor', 'slim charcoal bottle vase with eucalyptus sprig'],
  vase_ceramic_04: ['decor', 'low ribbed white vase with craspedia'],
  vase_brass: ['decor', 'hammered brass vase (built 0.36 m, use scale 0.5-0.7)'],
  picture_frame_standing: ['decor', 'standing oak photo frame 20x25 with print; front +Z'],
  picture_frame_standing_02: ['decor', 'standing black landscape photo frame 20x15; front +Z'],
  candlesticks_brass: ['decor', 'brass candleholders (built ~1.8x, use scale ~0.55). variants: brass_candleholder_01 (trio on tray), brass_candleholder_02 (pair), brass_candleholder_03 (chamberstick)'],
  mantel_clock: ['decor', 'walnut napoleon-hat mantel clock, brass bezel; front +Z (built 0.32 m)'],
  basket_wicker: ['decor', 'rattan storage basket with linen liner and rope handles'],
  bowl_wood_02: ['kitchen', 'turned olive-wood bowl with walnuts (built 0.16 m, use scale ~1.5)'],
  kettle: ['kitchen', 'brushed-steel kettle, black handle; spout +Z'],
  pot_enamel: ['kitchen', 'teal enamelled cast-iron cocotte with lid'],
  pan_brass: ['kitchen', 'copper saute pan with brass handle (handle +X)'],
  cutting_board: ['kitchen', 'oak chopping board with baguette and chef knife (long axis X)'],
  fruit_bowl_wood: ['kitchen', 'teak fruit bowl with oranges and pears'],
  apple: ['kitchen', 'red-green apple'],
  lemon: ['kitchen', 'lemon'],
  wine_bottles: ['kitchen', 'wine bottles. variants: wine_bottles_01_bordeaux, wine_bottles_01_burgundy'],
  tea_set: ['kitchen', 'porcelain tea set on ash tray (built 0.46 m, use scale ~0.7)'],
  laptop: ['office', 'open aluminium laptop, emissive screen (built 0.53 m wide, use scale ~0.62); screen faces +Z'],
  binder: ['office', 'lever-arch binder lying flat with papers (stackable via drop)'],
  stationery: ['office', 'pen pot, spiral notepad, pencil, sticky notes'],
  alarm_clock: ['bedroom', 'sage twin-bell alarm clock; front +Z'],
  rubber_duck: ['bath', 'yellow rubber duck (built 0.22 m, use scale ~0.4)'],
  laundry_basket_wicker: ['bath', 'round wicker laundry hamper, lid ajar, towel over the front rim'],
  stool_wood: ['bath', 'ash three-legged stool 0.46 m'],
  cleaner_bottle: ['bath', 'blue spray cleaner bottle with trigger'],
  lantern: ['lighting', 'black steel candle lantern with glass panes, emissive flame'],
  sofa_fabric_3seat: ['living', 'slate woven 3-seat sofa 2.2 m, piped cushions, scatter cushions, walnut legs; front +Z'],
  sofa_leather_2seat: ['living', 'cognac leather 2-seat sofa 1.6 m, tufted back cushions, black steel frame; front +Z'],
  ottoman: ['living', 'round sage boucle ottoman 0.55 m with piping'],
  throw_pillows: ['living', 'pair of leaning throw pillows (terracotta linen + ivory knit)'],
  tv_stand_cabinet: ['living', 'walnut media sideboard 1.8 m, slatted doors, soundbar bay, hairpin legs; front +Z'],
  dining_chair_modern: ['dining', 'oak dining chair with curved back rail and piped oat seat pad; front +Z'],
  dining_table_rect: ['dining', 'oak trestle dining table 2.0 x 0.95 m'],
  dining_table_round: ['dining', 'round 1.2 m oak dining table on white tulip base'],
  bar_stool_round: ['kitchen', 'counter stool 0.66 m, oak seat, black steel legs + footring'],
  dresser_drawers: ['bedroom', 'oak chest of 4 drawers with brass bar pulls, perfume + dish on top; front +Z'],
  nightstand_classic: ['bedroom', 'walnut 2-drawer nightstand with brass knobs, turned legs; front +Z'],
  nightstand_painted: ['bedroom', 'sage lacquer nightstand, drawer + open niche with book, oak top; front +Z'],
  wardrobe_cabinet: ['bedroom', 'two-door panelled oak wardrobe 1.1 x 0.6 x 2.1 m, brass pulls; front +Z'],
  // ---- P04 landscape / garden / outdoor / garage / potted plants (procedural stand-ins, same names as models.json).
  // Vegetation: alpha-MASK leaf materials (painted atlases), leaf cards with crown-blended normals.
  tree_island_01: ['garden', 'broad maple-like garden tree ~3.6 m (scaled 1.7-2.1x by site.json); leaf material leaves_maple'],
  tree_island_02: ['garden', 'two-stem silver birch ~4.2 m, white bark, airy round-leaf crown; leaf material leaves_birch'],
  tree_small: ['garden', 'olive-like multi-stem small tree ~3.9 m, grey-green lance leaves; leaf material leaves_olive'],
  shrub_02_a: ['garden', 'laurel-like evergreen shrub ~1.2 m'],
  shrub_02_b: ['garden', 'laurel-like evergreen shrub ~1.6 m'],
  shrub_02_c: ['garden', 'laurel-like evergreen shrub ~1.2 m, low and wide'],
  shrub_02_d: ['garden', 'laurel-like evergreen shrub ~1.7 m'],
  shrub_03: ['garden', 'boxwood-like small-leaved shrub. variants: shrub_03_a, shrub_03_b, shrub_03_c (0.9-1.2 m)'],
  shrub_04: ['garden', 'hydrangea-like flowering shrub ~1.7 m, lilac-blue mopheads'],
  shrub_sorrel: ['garden', 'wood-sorrel ground cover mounds. variants: shrub_sorrel_a..c'],
  grass_clump_medium: ['garden', 'grass clumps. variants: grass_clump_medium_a..c (0.35-0.55 m)'],
  grass_clump_medium_02: ['garden', 'grass clumps with straw tips. variants: grass_medium_02_a..d (0.3-0.52 m)'],
  grass_clump_bermuda: ['garden', 'low fine grass mats. variants: grass_clump_bermuda_a..c'],
  flower_gazania: ['garden', 'gazania clumps. variants: flower_gazania_a (orange), _b (yellow), _c (cream)'],
  plant_periwinkle: ['garden', 'periwinkle bedding plants. variants: plant_periwinkle_a (pink), _b (white), _c (magenta)'],
  rock_moss_set: ['garden', 'six mossy granite rocks 0.8-2 m. variants: rock_moss_set_01_rock01..06'],
  boulder: ['garden', 'weathered grey boulder ~1.3 m (normal + ORM reused by gabion stones)'],
  garden_gloves: ['garden', 'pair of garden gloves lying flat'],
  trowel: ['garden', 'hand trowel lying flat, tip +X'],
  fire_pit_stone: ['outdoor', 'dry-stacked stone fire pit 1.3 m with charred logs'],
  outdoor_table_chairs: ['outdoor', 'teak dining table 1.6x0.9 + 4 slatted chairs (table length along X)'],
  outdoor_sofa_wood: ['outdoor', 'sage painted wooden 2-seat garden sofa with linen cushions; front +Z'],
  outdoor_bench_modular: ['outdoor', 'concrete blocks + iroko slat bench 2.0 m'],
  picnic_table: ['outdoor', 'weathered wooden picnic table with attached benches 1.8 m (length along X)'],
  bollard_lamp: ['outdoor', 'anthracite garden bollard 0.78 m with emissive light window'],
  security_light: ['outdoor', 'wall LED floodlight with PIR sensor, tilted down; back -Z to wall'],
  aircon_unit: ['outdoor', 'split-AC outdoor condenser 0.85 m; back -Z to wall, fan grille +Z'],
  garden_hose: ['outdoor', 'wall-mounted hose reel with green hose + spray gun; back -Z to wall'],
  planter_pot_clay: ['outdoor', 'terracotta pot 0.5 m dia x 0.45 m, soil-filled'],
  planter_ceramic: ['outdoor', 'teal glazed egg planter 0.44 x 0.48 m, soil-filled'],
  planter_box_01: ['outdoor', 'corten raised planter box 1.2 x 0.4 x 0.45 m'],
  planter_box_02: ['outdoor', 'cedar plank planter box 0.8 x 0.5 x 0.5 m'],
  garden_sprinkler: ['outdoor', 'oscillating lawn sprinkler'],
  car_covered: ['garage', 'SUV under a grey fabric car cover 4.8 m; nose +Z'],
  garage_shelves_steel: ['garage', 'boltless galvanised shelving 1.2x0.45x1.8 m, decks at 0.04/0.42/0.82/1.22/1.62 m; back -Z'],
  garage_shelves_steel_narrow: ['garage', 'boltless galvanised shelving 0.6x0.35x1.8 m, decks at 0.04/0.42/0.82/1.22/1.62 m; back -Z'],
  shelves_steel_03: ['garage', 'anthracite steel shelving 1.5x0.5x1.5 m, 4 decks; back -Z'],
  tool_chest: ['garage', 'red rolling tool chest 0.68x1.0x0.46 m, 6 drawers; front +Z'],
  toolbox: ['garage', 'red steel toolbox 0.5 m (length along X)'],
  tool_cart: ['garage', 'blue 3-tray tool cart 0.8 m, handle at +X'],
  ladder_wood: ['garage', 'straight wooden ladder 2.4 m, built standing'],
  drill: ['garage', 'cordless drill on its battery, chuck +X'],
  tire_pump: ['garage', 'floor bicycle pump 0.62 m'],
  crate_plastic: ['garage', 'grey stacking crate 0.6x0.4x0.3 m'],
  box_cardboard: ['garage', 'taped cardboard box 0.5x0.35x0.35 m'],
  crate_wood: ['garage', 'slatted pine crate 0.6x0.4x0.36 m, open top'],
  watering_can: ['garage', 'galvanised watering can, spout +X'],
  bucket_wood: ['garage', 'coopered oak bucket with rope handle 0.3 m'],
  trash_can_metal: ['garage', 'galvanised ribbed dustbin with lid 0.73 m'],
  jerrycan: ['garage', 'olive steel jerrycan 20 l'],
  hand_truck: ['garage', 'red two-wheel hand truck 1.2 m'],
  broom: ['garage', 'push broom 1.43 m, built standing head down'],
  spade: ['garage', 'garden spade 1.09 m, built standing blade down'],
  plant_potted_01: ['decor', 'snake plant in white cylinder pot 0.73 m'],
  plant_potted_02: ['decor', 'fiddle-leaf fig in charcoal pot 1.5 m'],
  plant_succulent_small: ['decor', 'echeveria rosette in terracotta pot 0.11 m'],
  plant_succulent_cheiridopsis: ['decor', 'cheiridopsis clumps in clay bowls. variants: plant_succulent_cheiridopsis_a, _b'],
  plant_calathea_a: ['decor', 'calathea orbifolia 0.39 m, plant only (base = soil; for the planter proc)'],
  plant_calathea_b: ['decor', 'calathea orbifolia 0.5 m, plant only'],
  plant_calathea_c: ['decor', 'calathea orbifolia 0.45 m, plant only'],
  plant_calathea_d: ['decor', 'calathea orbifolia 0.67 m, plant only'],
  plant_calathea_e: ['decor', 'calathea orbifolia 0.75 m, plant only'],
  plant_anthurium_a: ['decor', 'anthurium 0.41 m, red spathes, plant only'],
  plant_anthurium_b: ['decor', 'anthurium 0.44 m, red spathes, plant only'],
  plant_anthurium_c: ['decor', 'anthurium 0.43 m, white spathes, plant only'],
  plant_anthurium_d: ['decor', 'anthurium 0.53 m, pink spathes, plant only'],
  plant_anthurium_e: ['decor', 'anthurium 0.56 m, red spathes, plant only'],
  plant_anthurium_f: ['decor', 'anthurium 0.63 m, red spathes, plant only'],
  plant_pachira_a: ['decor', 'braided money tree 0.5 m, plant only'],
  plant_pachira_b: ['decor', 'braided money tree 0.85 m, plant only'],
  plant_pachira_c: ['decor', 'braided money tree 1.1 m, plant only'],
  plant_pachira_d: ['decor', 'braided money tree 1.4 m, plant only'],
  plant_fern_a: ['decor', 'boston fern 0.43 m, arching fronds, plant only'],
  plant_fern_b: ['decor', 'boston fern 0.59 m, plant only'],
  plant_fern_c: ['decor', 'boston fern 0.46 m, plant only'],
  plant_fern_d: ['decor', 'boston fern 0.68 m, plant only'],
  // ---- end P04 block
};
const mf = JSON.parse(fs.readFileSync(R + '/public/assets/manifest.json', 'utf8'));
for (const [name, [cat, use]] of Object.entries(PROPS)) {
  const pk = JSON.parse(fs.readFileSync(`${B}/${name}.pack.json`, 'utf8'));
  const meta = JSON.parse(fs.readFileSync(`${B}/${name}.json`, 'utf8'));
  const e = { file: `models/${name}.glb`, dims: pk.dims, tris: pk.tris, mb: pk.mb, category: cat, use, source: SOURCE };
  if (meta.variants) e.variants = meta.variants;
  mf.models[name] = e;
}
mf.models = Object.fromEntries(Object.entries(mf.models).sort(([a], [b]) => a.localeCompare(b)));
fs.writeFileSync(R + '/public/assets/manifest.json', JSON.stringify(mf, null, 1));
const cp = R + '/public/assets/CREDITS.md';
let md = fs.readFileSync(cp, 'utf8');
const line = `- Procedural props (CC0, built in Blender 5.2 by \`pipeline/props/*.py\`, no third-party data): ${Object.keys(PROPS).join(', ')}.`;
md = md.replace(/\n## Procedural models[\s\S]*$/, '');
md = md.trimEnd() + '\n\n## Procedural models\n\n' + line + '\n';
fs.writeFileSync(cp, md);
console.log('manifest models:', Object.keys(mf.models).length, '| added/updated', Object.keys(PROPS).length);
